services:
    tasks-app:
        container_name: tasks-app
        build: 
            context: .
            dockerfile: Dockerfile
        depends_on: 
            mssqlserver:
                condition: service_healthy

        environment: 
            ASPNETCORE_ENVIRONMENT: Development,
            RabbitMQ__Host: rabbitmq,
            RabbitMQ__Port: 5672,
        ports: 
           - "8080:8080"

    mssqlserver:
        container_name: mssqlserver
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports: 
            - 1422:1433
        volumes:
        - sqlserver_data:/data/db
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
        user: root
        healthcheck:
          test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S 127.0.0.1 -U SA -P YourStrong!Passw0rd -C -Q 'SELECT 1' || exit 1"]
          interval: 10s
          retries: 10
          start_period: 40s
          timeout: 3s

    rabbitmq: 
        container_name: rabbitmq
        image: rabbitmq:3-management
        ports:
          - "5672:5672"   # RabbitMQ broker port
          - "15672:15672" # RabbitMQ management plugin port
        environment:
          RABBITMQ_DEFAULT_USER: user
          RABBITMQ_DEFAULT_PASS: password
        healthcheck:
          test: ["CMD", "rabbitmq-diagnostics", "ping"]
          interval: 30s
          timeout: 10s
          retries: 5
        volumes:
          - rabbitmq_data:/var/lib/rabbitmq

volumes:
    sqlserver_data:
    rabbitmq_data:
    